version: "3.5"

services:
  app:
    image: apmaros/budgetdesk:latest
    secrets:
      - monzo_client_secret
      - monzo_acc_id
      - monzo_client_id
      - monzo_redirect_url
      - influxdb_org
      - influxdb_bucket
      - server_secret_key
      - influxdb_token_v3
      - influxdb_url
      - auth0_client_id
      - auth0_client_secret
      - auth0_api_base_url
      - auth0_callback_url
      - server_name
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"

  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb:/var/lib/influxdb
      - influxdb2:/var/lib/influxdb2
    configs:
      - source: influxdb_config
        target: /etc/influxdb2/config.yml
        uid: '1000'
        gid: '1000'
    environment:
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
    ports:
      - "8086:8086"
  redis:
    image: redis:alpine3.15
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

configs:
  influxdb_config:
    external: true
    name: influxdb_config

volumes:
  logvolume01: {}
  influxdb: {}
  influxdb2: {}
  grafana: {}
  redis: {}

secrets:
  monzo_client_secret:
    external: true
  monzo_acc_id:
    external: true
  monzo_client_id:
    external: true
  monzo_redirect_url:
    external: true
  influxdb_org:
    external: true
  influxdb_bucket:
    external: true
  server_secret_key:
    external: true
  influxdb_token_v3:
    external: true
  influxdb_url:
    external: true
  auth0_client_id:
    external: true
  auth0_client_secret:
    external: true
  auth0_api_base_url:
    external: true
  auth0_callback_url:
    external: true
  server_name:
    external: true
