version: '3.1'

services:
  app:
    image: apmaros/budgetdesk:latest
    secrets:
        - monzo_client_secret
        - monzo_acc_id
        - monzo_client_id
        - monzo_redirect_url
        - influxdb_url
        - influxdb_org
        - influxdb_bucket
        - server_secret_key
        - influxdb_token

    ports:
      - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  monzo_client_secret:
    external: true
  monzo_acc_id:
    external: true
  monzo_client_id:
    external: true
  monzo_redirect_url:
    external: true
  influxdb_url:
    external: true
  influxdb_org:
    external: true
  influxdb_bucket:
    external: true
  server_secret_key:
    external: true
  influxdb_token_v2:
    external: true
