version: "3.3"
services:
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    links:
      - influxdb

  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb:/var/lib/influxdb
      - influxdb2:/var/lib/influxdb2
      - ./influxdb-config.yml:/etc/influxdb2/config.yml
    environment:
      DOCKER_INFLUXDB_INIT_MODE: upgrade
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
    ports:
      - "8086:8086"

volumes:
  logvolume01: {}
  influxdb: {}
  influxdb2: {}
  grafana: {}
