name: deploy image

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build and push docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        APP_VERSION: ${{ github.sha }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: apmaros/budgetdesk
        snapshot: true
        tags: "latest"
        buildargs: APP_VERSION
    - name: install ssh key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: deploy api
      run: docker --host ${{ secrets.DOCKER_SWARM_HOST }} stack deploy -c infra-stack.yml dataengine
